[[redirects]]
  from = "/v2"
  to = "https://tigs.mom/.netlify/functions/oci-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/v2/*"
  to = "https://ghcr.io/v2/beryju/:splat"
  status = 200
  force = true
