[[redirects]]
  from = "/v2"
  to = "https://beryjuorg.netlify.app/.netlify/functions/oci-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/v2/*"
  to = "https://beryju.docker.scarf.sh/v2/beryju/:splat"
  status = 200
  force = true
